use_frameworks!

platform :ios, '10.0'

target 'LYQRCodeGenerateAndScan_Example' do
  pod 'LYQRCodeGenerateAndScan', :path => '../'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGN_IDENTITY'] = ''
        end
      end
    end
  
end
