use_frameworks!

platform :ios, '10.0'

target 'LYQRCodeGenerateAndScan_Example' do
  pod 'LYQRCodeGenerateAndScan', :path => '../'

  target 'LYQRCodeGenerateAndScan_Tests' do
    inherit! :search_paths

    
  end
end
